### ISSUE TITLE
Missing Ara3D.Utils

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ara3d/IFC-toolkit#1]
Hi, where can i file Ara3D.Utils? Many thank!

**Comment by cdiggins** [comment]
You can find it at https://github.com/ara3d/ara3d, however I am in the progress of updating the projects so that all dependencies can be retrieved via Nuget.

**Comment by RyugaRyuzaki** [comment]
> You can find it at https://github.com/ara3d/ara3d, however I am in the progress of updating the projects so that all dependencies can be retrieved via Nuget.

HI, thank i got it. And a question, what if i use [helix-toolkit](https://github.com/helix-toolkit/helix-toolkit) to viewer?

**Comment by cdiggins** [comment]
> HI, thank i got it. And a question, what if i use [helix-toolkit](https://github.com/helix-toolkit/helix-toolkit) to viewer?

I think that is a great idea. I have started building a viewer based on WPF/Helix-toolkit here: https://github.com/ara3d/ara3d/tree/main/labs/Ara3D.Viewer.Wpf

If you aren't familiar with it, take a look at: https://github.com/xBimTeam/XbimWindowsUI.

**Comment by cdiggins** [comment]
@RyugaRyuzaki : just updated the readme with a link to the viewer and a screen-shot.
